# Generated by Django 5.2.5 on 2025-08-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('INR', 'Indian Rupee'), ('PKR', 'Pakistani Rupee'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan')], default='USD', max_length=3),
        ),
    ]
